kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-role
rules:
- apiGroups: ["extensions", "apps","kubernetes.io","autoscaling","networkpolicies.networking.k8s.io","policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims","configmaps","pods","pods/log","pods/portforward","pods/exec","replicationcontrollers","secrets","serviceaccounts","services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["resourcequotas","namespaces","pods/attach"]
  verbs: ["list","get"]  
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create"]  
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["kubedb.com","appcatalog.appscode.com","catalog.kubedb.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
